"""Add notes field to Reservation

Revision ID: 901718eb0abe
Revises: a611b5cb802d
Create Date: 2025-11-05 16:24:51.504420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901718eb0abe'
down_revision = 'a611b5cb802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
